import { Article } from './article'

export const ARTICLES : Article[] = [
    {
        id: '0',  
        name: 'pull',
        image: '/assets/images/imagesArticles/pulls.png',
        price: '4.99',
        color:['red', 'bleu'],
        category: 'pull',
        promotion: true, 
        nouveau : false,   
    },
    {
        id: '1',  
        name: 'chaussures de soirée ',
        image: '/assets/images/imagesArticles/chaussures.png',
        price: '4.99',
        color:['red', 'bleu'],
        category: 'chaussures',
        promotion: true,
        nouveau: true,
    },
    {
        id: '2',  
        name: 'pull de luxe ',
        image: '/assets/images/imagesArticles/1.png',
        price: '4.99',
        color:['red', 'bleu'],
        category: 'pull',
        promotion: false,
        nouveau: true,
    },
    {
        id: '3',  
        name: 'accessoire de lux ',
        image: '/assets/images/imagesArticles/accessoires.png',
        price: '4.99',
        color:['red', 'bleu'],
        category: 'accessoires',
        promotion: false,
        nouveau: false,
    },
    {
        id: '4',  
        name: 'pull de lux femme',
        image: '/assets/images/imagesArticles/2.png',
        price: '4.99',
        color:['red', 'bleu'],
        category: 'pull',
        promotion: true,
        nouveau : false,
    },
    {
        id: '5',  
        name: 'accessoire de femme moderne ',
        image: '/assets/images/imagesArticles/3.png',
        price: '4.99',
        color:['red', 'bleu'],
        category: 'accessoires',
        promotion: false,
        nouveau: true,
    },
];